// ANGLING DATABASE
// id, name, description, rarity, location
var anglingDB = TAFFY();
anglingDB.insert({"id":1,"name":"Sour Belly Guppy","description":"No belly pats for you sour puss!","rarity":"common","location":"thickets"});
anglingDB.insert({"id":2,"name":"Kyootie Fish","description":"Not to be confused with the Cutie Fish.","rarity":"common","location":"thickets"});
anglingDB.insert({"id":3,"name":"Lemonfish","description":"Pucker Up!","rarity":"uncommon","location":"thickets"});
anglingDB.insert({"id":4,"name":"Crusin' Carp","description":"Can reach speeds of up to 50mph if thrown hard enough!","rarity":"uncommon","location":"thickets"});
anglingDB.insert({"id":5,"name":"Slippery Sammy","description":"Goes great with green eggs and ham!","rarity":"rare","location":"thickets"});
anglingDB.insert({"id":6,"name":"Mushroom Trout","description":"Warning, not a psychadelic!","rarity":"common","location":"midwoods"});
anglingDB.insert({"id":7,"name":"Puff Pastry Fish","description":"Wait till puff rises before consuming.","rarity":"common","location":"midwoods"});
anglingDB.insert({"id":8,"name":"Pepper Pike","description":"Goes great with Salty Sailfish.","rarity":"uncommon","location":"midwoods"});
anglingDB.insert({"id":9,"name":"Salty Sailfish","description":"Goes great with Pepper Pike.","rarity":"uncommon","location":"midwoods"});
anglingDB.insert({"id":10,"name":"Olive Zander","description":"Found in the Olive Gardens.","rarity":"rare","location":"midwoods"});
anglingDB.insert({"id":11,"name":"Toothless Pirahna","description":"Dentures not included.","rarity":"common","location":"thorns"});
anglingDB.insert({"id":12,"name":"Seaweedcanth","description":"As ancient as your mom.","rarity":"common","location":"thorns"});
anglingDB.insert({"id":13,"name":"Cucumber Croc","description":"It's ancestor was the great Artichoke Ali.","rarity":"uncommon","location":"thorns"});
anglingDB.insert({"id":14,"name":"Baking Shark","description":"Suprisingly awful at pastries.","rarity":"uncommon","location":"thorns"});
anglingDB.insert({"id":15,"name":"Stuart Sturgeon","description":"Sturgeon General advises not to consume more than one a day.","rarity":"rare","location":"thorns"});
anglingDB.insert({"id":16,"name":"Aura Eel","description":"Tastes like all the colours of the rainbow.","rarity":"uncommon","location":"mount solitude"});
anglingDB.insert({"id":17,"name":"Miraculous Manta","description":"Named by the famous explorer Soosh Irwin.","rarity":"uncommon","location":"mount solitude"});
anglingDB.insert({"id":18,"name":"King Koi","description":"Best entertained by the Clown Fish!","rarity":"rare","location":"mount solitude"});

// HUNTING DATABASE
// id, name, description, type, difficulty, location
var huntingDB = TAFFY();
huntingDB.insert({"id":1,"name":"Dragon Fruit Fly","description":"Known to keep hordes of single coins.","difficulty":"easy","location":"thickets"});
huntingDB.insert({"id":2,"name":"Speedy Snail","description":"Reaches up to speeds of 5mphs. ","difficulty":"easy","location":"thickets"});
huntingDB.insert({"id":3,"name":"Peamouse","description":"Large enough to felt underneath 10 mattresses.","difficulty":"medium","location":"thickets"});
huntingDB.insert({"id":4,"name":"BEES","description":"...BEES?","difficulty":"hard","location":"thickets"});
huntingDB.insert({"id":5,"name":"Caraway Pidgeon","description":"Throwing caution to the wind.","difficulty":"easy","location":"midwoods"});
huntingDB.insert({"id":6,"name":"Fritter Pheasant","description":"Comes in apple, blueberry and cinnamon flavors.","difficulty":"medium","location":"midwoods"});
huntingDB.insert({"id":7,"name":"Raspberry Rabbit","description":"I will pet him and love him and call him George. ","difficulty":"medium","location":"midwoods"});
huntingDB.insert({"id":8,"name":"Pudding Deer","description":"Hunted for their chocolate filling.","difficulty":"hard","location":"midwoods"});
huntingDB.insert({"id":9,"name":"Spoop Spyder","description":"Not as dangerous as the spook spider.","difficulty":"easy","location":"thorns"});
huntingDB.insert({"id":10,"name":"Adamame Scorpion","description":"Boil in water and serve with salt.","difficulty":"medium","location":"thorns"});
huntingDB.insert({"id":11,"name":"Dijon Duck","description":"Goes great with mustard.","difficulty":"medium","location":"thorns"});
huntingDB.insert({"id":12,"name":"Menacing Clucker","description":"Beak of doom.","difficulty":"hard","location":"thorns"});
huntingDB.insert({"id":13,"name":"Haggishog","description":"A delicacy among kilted Sushi Dogs.","difficulty":"hard","location":"thorns"});
huntingDB.insert({"id":14,"name":"Bubbling Turtle","description":"A great pal during bath time adventures!","difficulty":"medium","location":"mount solitude"});
huntingDB.insert({"id":15,"name":"Wise Moo","description":"This beef gets straight A's!","difficulty":"medium","location":"mount solitude"});
huntingDB.insert({"id":16,"name":"Limerelk","description":"It's radiance is blinding. No wonder it can't be found.","difficulty":"hard","location":"mount solitude"});

// GATHERING DATABASE
// id, name, description, type, rarity, location
var gatheringDB = TAFFY();
gatheringDB.insert({"id":1,"name":"Dandepuffs","description":"Does not make for a dandy day with allergies.","type":"flower","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":2,"name":"Alri","description":"Considered pretty alri-ght by botanists.","type":"plant","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":3,"name":"Ipli","description":"Used by elder Sooshes to get back to their roots.","type":"root","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":4,"name":"Golips","description":"Particularly rare in The Thorns.","type":"flower","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":5,"name":"Maglia","description":"Mag-nificient in bouquets.","type":"flower","rarity":"rare","location":"thickets"});
gatheringDB.insert({"id":6,"name":"Cader","description":"Caters to your ailments.","type":"plant","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":7,"name":"Taca Weed","description":"Talks too much.","type":"plant","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":8,"name":"Poife","description":"Poifect in soups!","type":"root","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":9,"name":"Riri Root","description":"Riri good for colds.","type":"root","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":10,"name":"Strivy","description":"There's no known strivia about this plant.","type":"plant","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":11,"name":"Pickly Weed","description":"Oddly enough, quite common in The Thorns.","type":"plant","rarity":"common","location":"thorns"});
gatheringDB.insert({"id":12,"name":"Cowort Weed","description":"Can be applied directly to a wound for no effect.","type":"plant","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":13,"name":"Dinblee","description":"The only flower found in The Thorns.","type":"flower","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":14,"name":"Pinpin Root","description":"Often used to hold sewing needles.","type":"root","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":15,"name":"Skeel","description":"Often mistaken for the Dinblee flower.","type":"flower","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":16,"name":"Souplume","description":"Typically used in candy for the elderly.","type":"flower","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":17,"name":"Otlo","description":"Found in the lowest parts of Mount Solitude.","type":"plant","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":18,"name":"Loteus","description":"Early explorers thought they found the lotus plant...they were wrong.","type":"flower","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":19,"name":"Artmos","description":"Said to give 'god like powers', found in unreachable places.","type":"flower","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":20,"name":"Racing Shell","description":"Always targets first place.","type":"small animal items/drops","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":21,"name":"Peamouse Tail","description":"Can be felt under 3 mattresses.","type":"small animal items/drops","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":22,"name":"Draco Wings","description":"Not particularly rare, just easily damaged.","type":"small animal items/drops","rarity":"rare","location":"thickets"});
gatheringDB.insert({"id":23,"name":"Caraway Feather","description":"Not enough caution!","type":"small animal items/drops","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":24,"name":"Fritter Beak","description":"Designed easily to pluck berries.","type":"small animal items/drops","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":25,"name":"Raspberry Rabbit Foot","description":"Lucky for everyone except the rabbit.","type":"small animal items/drops","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":26,"name":"Pudding Horns","description":"Thought to cure diseases.","type":"small animal items/drops","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":27,"name":"Dijon Duck Feather","description":"Goes great with ketchup.","type":"small animal items/drops","rarity":"common","location":"thorns"});
gatheringDB.insert({"id":28,"name":"Edamame Husk","description":"Usually found after an Edamame Scorpion has moltded. Check your boot...","type":"small animal items/drops","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":29,"name":"Hagis Hide","description":"Often made into skirts for men.","type":"small animal items/drops","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":30,"name":"Cluckling Eggs","description":"Warning: Sitting on them does not make them hatch.","type":"small animal items/drops","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":31,"name":"Sage Milk","description":"For healthy wisdom development.","type":"small animal items/drops","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":32,"name":"Elder Bones","description":"Respect your elders!","type":"small animal items/drops","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":33,"name":"Malloberries","description":"Used to make marshmallos.","type":"berry","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":34,"name":"Funkaberry","description":"Only good when funky fresh.","type":"berry","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":35,"name":"Choco Bean","description":"It's not chocolate yet.","type":"vegetable","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":36,"name":"Oddvacado","description":"Only grown in equal numbers.","type":"fruit","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":37,"name":"Lymon","description":"Known to grow fur during the full moon.","type":"fruit","rarity":"rare","location":"thickets"});
gatheringDB.insert({"id":38,"name":"Haloshrooms","description":"Haloshrooms: Veggies Evolved.","type":"vegetable","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":39,"name":"Plumpberry","description":"A very curvaceous fruit.","type":"berry","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":40,"name":"Tartoro","description":"My neighbor Tartoro.","type":"vegetable","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":41,"name":"Gogi Berry","description":"Used in go-gurt.","type":"berry","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":42,"name":"Wanana","description":"I'M A WAH-NANAAAA!","type":"fruit","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":43,"name":"Roodabegga","description":"Just like the everything else in The Thorns.","type":"vegetable","rarity":"common","location":"thorns"});
gatheringDB.insert({"id":44,"name":"Mussle Sprout","description":"Absolute gains.","type":"vegetable","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":45,"name":"Furrian Fruit","description":"Liked by a select few.","type":"fruit","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":46,"name":"Cluckapea","description":"Coveted by the menacing cluckers.","type":"vegetable","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":47,"name":"Crocumber","description":"A group of them is called a murder.","type":"vegetable","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":48,"name":"Dew Drop","description":"Named after the only thing you can't find in Mount Solitude.","type":"berry","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":49,"name":"Toorange","description":"Named after its purple texture.","type":"fruit","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":50,"name":"Kamacaza","description":"Each year it pollinates by falling down the mountain.","type":"fruit","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":51,"name":"Sparkling Water","description":"Only the purest of water can be found in The Thickets.","type":"crafting","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":52,"name":"Hunnie Drops","description":"Gatherers have to comb quite densely to gather these.","type":"crafting","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":53,"name":"Glittering Stone","description":"A sparkling rock...neat.","type":"crafting","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":54,"name":"Kernel Puff","description":"Dangerous at hot temperatures.","type":"crafting","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":55,"name":"Panboo Sprout","description":"No two panboo sprouts ever look the same.","type":"crafting","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":56,"name":"Maglia Pollen","description":"Not so mag-nificient for allergies.","type":"crafting","rarity":"rare","location":"thickets"});
gatheringDB.insert({"id":57,"name":"Magic Powder","description":"Scientically proven to work.","type":"crafting","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":58,"name":"Lumi Powder","description":"Often gathered at night.","type":"crafting","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":59,"name":"Glu Moss","description":"Gatherers frequently have to pry off woodland creatures.","type":"crafting","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":60,"name":"Mushi Sap","description":"Gatherers go in pairs to stop one another from eating it on their trip.","type":"crafting","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":61,"name":"Star Shard","description":"Valued by astrologists.","type":"crafting","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":62,"name":"Ordinary Stick","description":"Nothing suspicious here.","type":"crafting","rarity":"common","location":"thorns"});
gatheringDB.insert({"id":63,"name":"Pleather","description":"The only soft thing in The Thorns.","type":"crafting","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":64,"name":"Glittering Gem","description":"Often confused with the glittering stone.","type":"crafting","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":65,"name":"Whispering Vine","description":"Only the foolish try to hear what it is whispering.","type":"crafting","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":66,"name":"Rotting Orchid","description":"Due to how delicious it tastes, it's protected until it rots.","type":"crafting","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":67,"name":"Enchanting Crystal","description":"Absolutely ordinary.","type":"crafting","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":68,"name":"Radiand Powder","description":"Caution: Does not cause mutations.","type":"crafting","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":69,"name":"Planetes Stone","description":"You've got a whole world in your hands.","type":"crafting","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":70,"name":"Litter Bit","description":"A bit of rubbish right here.","type":"miscellaneous","rarity":"common","location":"thickets"});
gatheringDB.insert({"id":71,"name":"Rainbow Yarn","description":"Does not come in purple.","type":"miscellaneous","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":72,"name":"Wheattie","description":"Used to make bread. Just bread.","type":"miscellaneous","rarity":"rare","location":"thickets"});
gatheringDB.insert({"id":73,"name":"Glass Shard","description":"Ow! Why would you pick this up?","type":"miscellaneous","rarity":"common","location":"midwoods"});
gatheringDB.insert({"id":74,"name":"Sewing Needle","description":"Make from Pin Pin Roots.","type":"miscellaneous","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":75,"name":"Colourful Ribbon","description":"Like wearing a rainbow!","type":"miscellaneous","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":76,"name":"Pouty Pebbles","description":"One of the many miserable things in the Thorns.","type":"miscellaneous","rarity":"common","location":"thorns"});
gatheringDB.insert({"id":77,"name":"Spilled Ink","description":"Perfectly okay to cry over this.","type":"miscellaneous","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":78,"name":"Golden Apple","description":"A notch above the rest!","type":"miscellaneous","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":79,"name":"Powerless Crystal","description":"Filled with unlimited potential.","type":"miscellaneous","rarity":"uncommon","location":"mount solitude"});
gatheringDB.insert({"id":80,"name":"Stardust Pouch","description":"Not actually made from stardust.","type":"miscellaneous","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":81,"name":"Empty Bottle","description":"Filled with endless possibilities.","type":"treasures","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":82,"name":"Origami Critter","description":"A friendly reminder that we all come in different shapes and sizes.","type":"treasures","rarity":"uncommon","location":"thickets"});
gatheringDB.insert({"id":83,"name":"Cleanse Bead","description":"Some think it to be a fallen bead from Inekami's Neclace.","type":"treasures","rarity":"rare","location":"thickets"});
gatheringDB.insert({"id":84,"name":"Dream Catcher","description":"A sacred ward against nightmares,","type":"treasures","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":85,"name":"Misplaced Key","description":"Whelp, another inconvenience fee.","type":"treasures","rarity":"uncommon","location":"midwoods"});
gatheringDB.insert({"id":86,"name":"Celestial Note","description":"Experts cannot agree if it's a G or D sharp.","type":"treasures","rarity":"rare","location":"midwoods"});
gatheringDB.insert({"id":87,"name":"Lost Cloth","description":"Yet another inconcenience fee.","type":"treasures","rarity":"uncommon","location":"thorns"});
gatheringDB.insert({"id":88,"name":"Love Bead","description":"The only thing to love about the Thorns.","type":"treasures","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":89,"name":"Ancient Totem","description":"In the past it held great power, now it's held on a mantel piece.","type":"treasures","rarity":"rare","location":"thorns"});
gatheringDB.insert({"id":90,"name":"Lunar Charm","description":"It's power is out of this world.","type":"treasures","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":91,"name":"Solar Scale","description":"The weight of the world rests on this scale.","type":"treasures","rarity":"rare","location":"mount solitude"});
gatheringDB.insert({"id":92,"name":"The Great Soosh's Relic","description":"Holds infinite power to those who can wield it.","type":"treasures","rarity":"rare","location":"mount solitude"});

// MINING DATABASE
// id, name, description, type, rarity, location
var miningDB = TAFFY();
miningDB.insert({"id":1,"name":"Tasteless Dirt","description":"Oddly full of flavor.","rarity":"common","location":"thickets"});
miningDB.insert({"id":2,"name":"Smokey Coal","description":"Advised to be kept well ventilated.","rarity":"common","location":"thickets"});
miningDB.insert({"id":3,"name":"Molding Clay","description":"Great for arts and crafts!","rarity":"uncommon","location":"thickets"});
miningDB.insert({"id":4,"name":"Gobblestone","description":"Careful, it might gobble you up!","rarity":"uncommon","location":"thickets"});
miningDB.insert({"id":5,"name":"Shining Iron","description":"Could use a polsh.","rarity":"rare","location":"thickets"});
miningDB.insert({"id":6,"name":"Jelly Sponge","description":"The area around it is oddly dry.","rarity":"common","location":"midwoods"});
miningDB.insert({"id":7,"name":"Emari","description":"Often mistaken for Jadrite.","rarity":"common","location":"midwoods"});
miningDB.insert({"id":8,"name":"Lumistone","description":"Easily mined at night.","rarity":"uncommon","location":"midwoods"});
miningDB.insert({"id":9,"name":"Shinzimite","description":"Grows about leg height.","rarity":"uncommon","location":"midwoods"});
miningDB.insert({"id":10,"name":"Starlight Quartz","description":"On rare occassions can be found inside Lumistones.","rarity":"rare","location":"midwoods"});
miningDB.insert({"id":11,"name":"Boompowder","description":"The first discoverers learned quickly to run from the sound of fizzling.","rarity":"common","location":"thorns"});
miningDB.insert({"id":12,"name":"Grumpval","description":"Yet another miserable aspect of The Thorns.","rarity":"uncommon","location":"thorns"});
miningDB.insert({"id":13,"name":"Evisite","description":"Originally found elsehwere, everyone oddly avoided The Thorns when mining.","rarity":"uncommon","location":"thorns"});
miningDB.insert({"id":14,"name":"Fearnyx","description":"Surprisingly the least of your worries in The Thorns.","rarity":"rare","location":"thorns"});
miningDB.insert({"id":15,"name":"Malinite","description":"The most of your worries in The Thorns.","rarity":"rare","location":"thorns"});
miningDB.insert({"id":16,"name":"Eternal Ice","description":"Warning: Do not ingest.","rarity":"uncommon","location":"mount solitude"});
miningDB.insert({"id":17,"name":"Etoilite","description":"Found only by the most lucky and unlucky of miners.","rarity":"rare","location":"mount solitude"});
miningDB.insert({"id":18,"name":"Radiand","description":"The wildlife seems different around pockets of these minerals.","rarity":"rare","location":"mount solitude"});

// WOOD-CUTTING DATABASE
// id, logName, treeName, description, difficulty, location
var woodcuttingDB = TAFFY();
woodcuttingDB.insert({"id":1,"logName":"Panboo Logs","treeName":"Panboo Tree","description":"Due to its softness, it's often cut by beginners.","difficulty":"easy","location":"thickets"});
woodcuttingDB.insert({"id":2,"logName":"Nucta Logs","treeName":"Nuctaris","description":"Due to its dense bark, it is often kept safe from bugs.","difficulty":"medium","location":"thickets"});
woodcuttingDB.insert({"id":3,"logName":"Palma Logs","treeName":"Palmadora","description":"Its sheer size makes it easy to find, hard to cut.","difficulty":"hard","location":"thickets"});
woodcuttingDB.insert({"id":4,"logName":"Cola Logs","treeName":"Colacap","description":"Popularly used for boats due to its abundance.","difficulty":"easy","location":"midwoods"});
woodcuttingDB.insert({"id":5,"logName":"Mushi Logs","treeName":"Mushishroo","description":"A staple in furniture marking.","difficulty":"medium","location":"midwoods"});
woodcuttingDB.insert({"id":6,"logName":"Pumpki Logs","treeName":"Pumpkable","description":"It's tradition, once a year, to carve faces into these trees.","difficulty":"hard","location":"midwoods"});
woodcuttingDB.insert({"id":7,"logName":"Grizzled Logs","treeName":"Grizzlybark","description":"Yet another unBEARable thing about The Thorns.","difficulty":"medium","location":"thorns"});
woodcuttingDB.insert({"id":8,"logName":"Spoop Logs","treeName":"Spoop Tree","description":"Due to their hard to cut nature, wood-cutters are awarded the title Spoop Dog for cutting them.","difficulty":"medium","location":"thorns"});
woodcuttingDB.insert({"id":9,"logName":"Will Logs","treeName":"Willpine","description":"Often used in smithing.","difficulty":"hard","location":"thorns"});
woodcuttingDB.insert({"id":10,"logName":"Ether Logs","treeName":"Etheroak","description":"Its sap is highly flammable.","difficulty":"medium","location":"mount solitude"});
woodcuttingDB.insert({"id":11,"logName":"Cyth Logs","treeName":"Cythical Tree","description":"Do it.","difficulty":"hard","location":"mount solitude"});